quarkus:
    http:
        cors:
            ~: true
            origins: "*"
        limits:
            max-body-size: 100M
        port: 8080
    resteasy:
        ignore-application-classes: true
    index-dependency:
        resteasy-multipart:
            group-id: org.jboss.resteasy
            artifact-id: resteasy-multipart-provider
quinimbus:
    binary:
        stores:
            ${artifactId}:
                type: file
                rootPath: ./data/binary
        persistence-integration:
            schemas:
                ${artifactId}:
                    store: ${artifactId}
    persistence:
        schemas:
            ${artifactId}:
                type: record
                classes:
                    - ${package}.domain.BlogEntry
                    - ${package}.domain.BlogEntryComment
                    - ${package}.domain.Category
        storages:
            ${artifactId}:
                type: mongo
                schema: ${artifactId}
                host: localhost
                username: mongoroot
                password: mongorootpassword