name: build-deploy-release

on:
  push:
    tags:
      - '\d+.\d+.\d+'

permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Build with Maven
        working-directory: ./archetype
        run: mvn --batch-mode -Prelease verify
      - name: Deploy package to repository
        working-directory: ./archetype
        env:
          REPOUSER: ${{ secrets.repouser }}
          REPOPASS: ${{ secrets.repopass }}
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>quinimbus-snapshots</id><username>\${env.REPOUSER}</username><password>\${env.REPOPASS}</password></server><server><id>quinimbus-releases</id><username>\${env.REPOUSER}</username><password>\${env.REPOPASS}</password></server></servers></settings>" > ~/.m2/settings.xml
          mvn -DskipTests -Prelease deploy
      - name: Create Release
        uses: softprops/action-gh-release@v2